# Generated by Django 5.2 on 2025-04-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='role',
            field=models.CharField(default='Intern', max_length=100),
        ),
    ]
