# Generated by Django 5.2 on 2025-04-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_internship_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='roll_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
